/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoride.ui;


import ecoride.models.Booking;
import ecoride.models.Customer;
import ecoride.models.Vehicle;
import ecoride.services.EcoRideSystem;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Banuka
 */
public class BookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingForm.class.getName());

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
    initComponents();
    generateBookingId();
    lblBookingDate.setText(LocalDate.now().toString());
    fillCustomerCombo();
    fillVehicleCombo();
    loadBookingTable();

    }

    private void generateBookingId() {
    int nextId = EcoRideSystem.bookings.size() + 1;
    lblBookingId.setText("B" + nextId);
}

    private void loadComboBoxes() {

    // Load customers
    cmbCustomer.removeAllItems();
    for (Customer c : EcoRideSystem.customers) {
        cmbCustomer.addItem(c.getCustomerId() + " - " + c.getName());
    }

    // Load available vehicles
    cmbVehicle.removeAllItems();
    for (Vehicle v : EcoRideSystem.vehicles) {
        if (v.getStatus().equals("Available")) {
            cmbVehicle.addItem(v.getCarId() + " - " + v.getModel());
        }
    }
}
    //Booking Table
    private void loadBookingTable() {
    String[] cols = {"Booking ID", "Customer", "Vehicle", "Booking Date", "Rental Date", "Days", "Total KM"};
    Object[][] data = new Object[EcoRideSystem.bookings.size()][7];

    for (int i = 0; i < EcoRideSystem.bookings.size(); i++) {
        Booking b = EcoRideSystem.bookings.get(i);
        data[i][0] = b.getBookingId();
        data[i][1] = b.getCustomer().getName();
        data[i][2] = b.getVehicle().getModel();
        data[i][3] = b.getBookingDate().toString();
        data[i][4] = b.getRentalDate().toString();
        data[i][5] = b.getRentalDays();
        data[i][6] = b.getTotalKm();
    }

    tblBookings.setModel(new DefaultTableModel(data, cols));
}

    
    private Customer findCustomerById(String id) {
    for (Customer c : EcoRideSystem.customers) {
        if (c.getCustomerId().equals(id)) return c;
    }
    return null;
}
    
    private Vehicle findVehicleById(String id) {
    for (Vehicle v : EcoRideSystem.vehicles) {
        if (v.getCarId().equals(id)) return v;
    }
    return null;
}

    private void fillCustomerCombo() {
    cmbCustomer.removeAllItems();
    for (Customer c : EcoRideSystem.customers) {
        cmbCustomer.addItem(c.getCustomerId() + " - " + c.getName());
    }
}

private void fillVehicleCombo() {
    cmbVehicle.removeAllItems();
    for (Vehicle v : EcoRideSystem.vehicles) {
        if (v.getStatus().equals("Available")) {
            cmbVehicle.addItem(v.getCarId() + " - " + v.getModel());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBookingId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbVehicle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblBookingDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRentalDays = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookings = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BookingForm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Booking ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblBookingId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBookingId.setForeground(new java.awt.Color(255, 255, 255));
        lblBookingId.setText("_");
        jPanel1.add(lblBookingId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cmbCustomer.setBackground(new java.awt.Color(102, 102, 102));
        cmbCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehicle");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        cmbVehicle.setBackground(new java.awt.Color(102, 102, 102));
        cmbVehicle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cmbVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 190, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Booking Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblBookingDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBookingDate.setForeground(new java.awt.Color(255, 255, 255));
        lblBookingDate.setText("_");
        jPanel1.add(lblBookingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rental Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel1.add(txtRentalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rental Days");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(txtRentalDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total KM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(auto 0)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(153, 255, 153));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 153, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 80, -1));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 153, 153));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 90, -1));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 840, 30));

        tblBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBookings);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 440, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        
            try {
        String bookingId = lblBookingId.getText();
        LocalDate bookingDate = LocalDate.now();

        String customerSelection = (String) cmbCustomer.getSelectedItem();
        String vehicleSelection = (String) cmbVehicle.getSelectedItem();

        if (customerSelection == null || vehicleSelection == null) {
            JOptionPane.showMessageDialog(this, "Please select customer and vehicle.");
            return;
        }

        Customer customer = findCustomerById(customerSelection.split(" - ")[0]);
        Vehicle vehicle = findVehicleById(vehicleSelection.split(" - ")[0]);

        LocalDate rentalDate = LocalDate.parse(txtRentalDate.getText());
        int rentalDays = Integer.parseInt(txtRentalDays.getText());

        // BUSINESS RULE: Rental must be booked 3 days early
        if (rentalDate.isBefore(bookingDate.plusDays(3))) {
            JOptionPane.showMessageDialog(this, "Booking must be made at least 3 days before rental date.");
            return;
        }

        Booking booking = new Booking(
            bookingId,
            customer,
            vehicle,
            bookingDate,
            rentalDate,
            rentalDays,
            0 // default KM
        );

        EcoRideSystem.bookings.add(booking);

        loadBookingTable();
        generateBookingId();

        JOptionPane.showMessageDialog(this, "Booking added successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid input. Please check rental date/days.");
    }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblBookings.getSelectedRow();
if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a booking to update.");
    return;
}

Booking b = EcoRideSystem.bookings.get(row);

// customer can change
String customerId = cmbCustomer.getSelectedItem().toString().split(" - ")[0];
Customer customer = findCustomerById(customerId);
b.setCustomer(customer);

// rental date
LocalDate rentalDate = LocalDate.parse(txtRentalDate.getText());
b.setRentalDate(rentalDate);

// days
int days = Integer.parseInt(txtRentalDays.getText());
b.setRentalDays(days);

loadBookingTable();
JOptionPane.showMessageDialog(this, "Booking updated!");

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblBookings.getSelectedRow();
if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a booking to delete.");
    return;
}

Booking b = EcoRideSystem.bookings.get(row);

// make vehicle available again
b.getVehicle().setStatus("Available");

EcoRideSystem.bookings.remove(row);

loadBookingTable();
generateBookingId();

JOptionPane.showMessageDialog(this, "Booking deleted!");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cmbCustomer.setSelectedIndex(0);
        cmbVehicle.setSelectedIndex(0);
        txtRentalDate.setText("");
        txtRentalDays.setText("");
        generateBookingId();

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookingDate;
    private javax.swing.JLabel lblBookingId;
    private javax.swing.JTable tblBookings;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtRentalDays;
    // End of variables declaration//GEN-END:variables
}
