/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoride.ui;

import javax.swing.JOptionPane;
import ecoride.ui.Dashboard;

/**
 *
 * @author Banuka
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabel = new javax.swing.JLabel();
        btnVehicles = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnBookings = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnInvoices = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabel.setForeground(new java.awt.Color(255, 255, 255));
        JLabel.setText("EcoRide - Dashboard");
        jPanel1.add(JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        btnVehicles.setBackground(new java.awt.Color(153, 153, 153));
        btnVehicles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehicles.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicles.setText("Manage Vehicles");
        btnVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiclesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 60));

        btnCustomers.setBackground(new java.awt.Color(153, 153, 153));
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomers.setText("Register Customer");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, 60));

        btnBookings.setBackground(new java.awt.Color(153, 153, 153));
        btnBookings.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBookings.setForeground(new java.awt.Color(255, 255, 255));
        btnBookings.setText("Create Booking");
        btnBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingsActionPerformed(evt);
            }
        });
        jPanel1.add(btnBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 170, 60));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search Bookings");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 180, 60));

        btnInvoices.setBackground(new java.awt.Color(204, 204, 204));
        btnInvoices.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInvoices.setForeground(new java.awt.Color(51, 51, 51));
        btnInvoices.setText("Invoices");
        btnInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 200, 80));

        btnExit.setBackground(new java.awt.Color(102, 102, 102));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 153, 153));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 770, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiclesActionPerformed
            // open VehicleForm
    VehicleForm vf = new VehicleForm();
    vf.setLocationRelativeTo(this); 
    vf.setVisible(true);
    }//GEN-LAST:event_btnVehiclesActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
    CustomerForm cf = new CustomerForm();
    cf.setLocationRelativeTo(this);
    cf.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingsActionPerformed
    BookingForm bf = new BookingForm();
    bf.setLocationRelativeTo(this);
    bf.setVisible(true);
    }//GEN-LAST:event_btnBookingsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    SearchBookingForm sf = new SearchBookingForm();
    sf.setLocationRelativeTo(this);
    sf.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoicesActionPerformed
    InvoiceForm inf = new InvoiceForm();
    inf.setLocationRelativeTo(this);
    inf.setVisible(true);
    }//GEN-LAST:event_btnInvoicesActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            // polite exit
    int confirm = JOptionPane.showConfirmDialog(this, "Exit EcoRide?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton btnBookings;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInvoices;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnVehicles;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
