/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoride.ui;

import ecoride.models.Booking;
import ecoride.services.EcoRideSystem;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author Banuka
 */
public class SearchBookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchBookingForm.class.getName());

    /**
     * Creates new form SearchBookingForm
     */
    public SearchBookingForm() {
    initComponents();
    loadFilters();
    clearTable();   // ← start with an empty table
    }

    /**
     * Load the available filter options into the combo box.
     */
    private void loadFilters() {
    cmbFilter.removeAllItems();
    cmbFilter.addItem("All");
    cmbFilter.addItem("Booking ID");
    cmbFilter.addItem("Customer ID");
    cmbFilter.addItem("Vehicle ID");
    cmbFilter.addItem("Booking Date");
}
   
    private void loadAllResults() {
    String[] cols = {"Booking ID","Customer","Vehicle","Booking Date","Rental Date","Days","KM"};
    Object[][] data = new Object[EcoRideSystem.bookings.size()][7];

            // Fill table row-by-row
    for (int i = 0; i < EcoRideSystem.bookings.size(); i++) {
        Booking b = EcoRideSystem.bookings.get(i);
        data[i][0] = b.getBookingId();
        data[i][1] = b.getCustomer().getCustomerId() + " - " + b.getCustomer().getName();
        data[i][2] = b.getVehicle().getCarId() + " - " + b.getVehicle().getModel();
        data[i][3] = b.getBookingDate().toString();
        data[i][4] = b.getRentalDate().toString();
        data[i][5] = b.getRentalDays();
        data[i][6] = b.getTotalKm();
    }

    tblSearchResults.setModel(new DefaultTableModel(data, cols));
}
    
    private void performSearch() {
    String filter = cmbFilter.getSelectedItem().toString();
    String query = txtSearch.getText().trim().toLowerCase();

    ArrayList<Booking> results = new ArrayList<>();

            // Loop through all bookings and filter based on user selection
    for (Booking b : EcoRideSystem.bookings) {
        switch (filter) {
            case "All":
                results.add(b);
                break;

            case "Booking ID":
                if (b.getBookingId().equalsIgnoreCase(query)) results.add(b);
                break;

            case "Customer ID":
                if (b.getCustomer().getCustomerId().equalsIgnoreCase(query) ||
                    b.getCustomer().getName().toLowerCase().contains(query))
                    results.add(b);
                break;

            case "Vehicle ID":
                if (b.getVehicle().getCarId().equalsIgnoreCase(query) ||
                    b.getVehicle().getModel().toLowerCase().contains(query))
                    results.add(b);
                break;

            case "Booking Date":  
                if (b.getBookingDate().toString().equals(query)) results.add(b);
                break;
        }
    }

    // show results in table
    String[] cols = {"Booking ID","Customer","Vehicle","Booking Date","Rental Date","Days","KM"};
    Object[][] data = new Object[results.size()][7];

    for (int i = 0; i < results.size(); i++) {
        Booking b = results.get(i);
        data[i][0] = b.getBookingId();
        data[i][1] = b.getCustomer().getCustomerId() + " - " + b.getCustomer().getName();
        data[i][2] = b.getVehicle().getCarId() + " - " + b.getVehicle().getModel();
        data[i][3] = b.getBookingDate().toString();
        data[i][4] = b.getRentalDate().toString();
        data[i][5] = b.getRentalDays();
        data[i][6] = b.getTotalKm();
    }

    tblSearchResults.setModel(new DefaultTableModel(data, cols));
}

    
    private void clearTable() {
    tblSearchResults.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Booking ID","Customer","Vehicle","Booking Date","Rental Date","Days","KM"}
    ));
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Search Booking");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search (Booking ID)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtSearch.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filter By");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        cmbFilter.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(cmbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, -1));

        btnSearch.setBackground(new java.awt.Color(102, 102, 102));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 600, 30));

        tblSearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSearchResults);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        performSearch();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtSearch.setText("");
    cmbFilter.setSelectedIndex(0);
    clearTable();   
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchBookingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSearchResults;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
