/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoride.ui;

import ecoride.services.EcoRideSystem;
import ecoride.models.Vehicle;


/**
 *
 * @author Banuka
 */
public class VehicleForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VehicleForm.class.getName());

    /**
     * Creates new form VehicleForm
     */
    public VehicleForm() {
        initComponents();
        
    // fill combo boxes
    cmbCategory.addItem("Compact Petrol");
    cmbCategory.addItem("Hybrid");
    cmbCategory.addItem("Electric");
    cmbCategory.addItem("Luxury SUV");

    cmbStatus.addItem("Available");
    cmbStatus.addItem("Reserved");
    cmbStatus.addItem("Under Maintenance");

    generateCarId();  // ⭐ Add this
    loadVehicleTable();
    }
        
    private void generateCarId() {
    int nextId = EcoRideSystem.vehicles.size() + 1;
    lblCarId.setText("C" + nextId);
}
    //Vehicle Table
    private void loadVehicleTable() {
    String[] columnNames = {"Car ID", "Model", "Category", "Rate", "Status"};
    Object[][] data = new Object[EcoRideSystem.vehicles.size()][5];

    for (int i = 0; i < EcoRideSystem.vehicles.size(); i++) {
        Vehicle v = EcoRideSystem.vehicles.get(i);
        data[i][0] = v.getCarId();
        data[i][1] = v.getModel();
        data[i][2] = v.getCategory();
        data[i][3] = v.getDailyRate();
        data[i][4] = v.getStatus();
    }

    tblVehicles.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        lblCarId = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("VehicleForm");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 220, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Model");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtModel.setBackground(new java.awt.Color(153, 153, 153));
        txtModel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        cmbCategory.setBackground(new java.awt.Color(153, 153, 153));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Daily Rate");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtRate.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        cmbStatus.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(153, 255, 153));
        btnAdd.setText("Add Vehicle");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 40));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 153, 255));
        btnUpdate.setText("Update Vehicle");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Delete Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 40));

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Model", "Category", "Rate", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblVehicles);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 480, 250));

        lblCarId.setBackground(new java.awt.Color(204, 204, 204));
        lblCarId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCarId.setForeground(new java.awt.Color(204, 204, 204));
        lblCarId.setText("_");
        jPanel1.add(lblCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 480, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     //Add Button
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String carId = lblCarId.getText();  // auto-generated
    String model = txtModel.getText().trim();
    if (model.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter the model.");
        return;
    }

    String category = cmbCategory.getSelectedItem().toString();
    double rate;
    try {
        rate = Double.parseDouble(txtRate.getText().trim());
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid daily rate.");
        return;
    }
    String status = cmbStatus.getSelectedItem().toString();

    Vehicle v = new Vehicle(carId, model, category, rate, status);
    EcoRideSystem.vehicles.add(v);

    loadVehicleTable();
    generateCarId();  // prepare next ID

    // clear the model field so user knows it's added
    txtModel.setText("");
    txtRate.setText("");

    javax.swing.JOptionPane.showMessageDialog(this, "Vehicle added!");
    }//GEN-LAST:event_btnAddActionPerformed
   
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         int row = tblVehicles.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a vehicle to update.");
        return;
    }

    Vehicle v = EcoRideSystem.vehicles.get(row);

    // Car ID should remain the auto-generated label value
    // v.setCarId(lblCarId.getText());

    v.setModel(txtModel.getText());
    v.setCategory(cmbCategory.getSelectedItem().toString());
    try {
        v.setDailyRate(Double.parseDouble(txtRate.getText()));
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid rate. Please enter a number.");
        return;
    }
    v.setStatus(cmbStatus.getSelectedItem().toString());

    loadVehicleTable();

    javax.swing.JOptionPane.showMessageDialog(this, "Vehicle updated!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int row = tblVehicles.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a vehicle to delete.");
        return;
    }

    EcoRideSystem.vehicles.remove(row);

    loadVehicleTable();

    javax.swing.JOptionPane.showMessageDialog(this, "Vehicle deleted!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
           String category = cmbCategory.getSelectedItem().toString();

    switch (category) {
        case "Compact Petrol":
            txtRate.setText("8000");
            break;
        case "Hybrid":
            txtRate.setText("10000");
            break;
        case "Electric":
            txtRate.setText("12000");
            break;
        case "Luxury SUV":
            txtRate.setText("18000");
            break;
    }
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
            new Dashboard().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VehicleForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
